# Generated by Django 4.1.5 on 2023-03-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hikaro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='question',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='english_meaning',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storedImages'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='japanese_sentence',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
